# Copy to .streamlit/secrets.toml and fill in:
# Option A: Public/SAS URL (recommended)
DATA_URL = "https://trafficsprostorage.blob.core.windows.net/traffic-data?sp=r&st=2025-11-05T10:44:17Z&se=2025-11-20T18:59:17Z&spr=https&sv=2024-11-04&sr=c&sig=yKRqsEgTSxnrCH%2Fct%2FKU6x%2F98wp%2B%2FY2OFgo6I%2FpX5yk%3D"

# Option B: Private Blob with SDK (only if you wonâ€™t use SAS)
# AZURE_STORAGE_ACCOUNT = "trafficsprostorage"
# AZURE_STORAGE_KEY = "REPLACE_ME_IN_LOCAL_secrets.toml"
# AZURE_CONTAINER = "traffic-data"
# AZURE_BLOB = "traffic_with_time.parquet"
